CREATE TABLE job (
    id SERIAL NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(32) NOT NULL
);

CREATE TABLE user (
    id SERIAL NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(64) NOT NULL,
    job_id INT,
    FOREIGN KEY (job_id) REFERENCES job(id)
);